[package]
name = "ltrait"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
tokio-stream = "0.1.17"

[dependencies.rayon]
version = "1.10.0"
optional = true

[dev-dependencies]
tokio = { version = "1.43.0", features = ["full"] }

[features]
parallel = ["dep:rayon"]
