[package]
name = "ltrait"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
async-trait = "0.1.86"
color-eyre = "0.6.3"
tokio-stream = "0.1.17"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["full"] }
